Repository openshift/ironic-rhcos-downloader, pull requests merged in 2019-11, with the labels that each got.

#9 Handle sha256 query string added in the rhcos image url
  get-resource.sh
Labels: size/XS

#10 Remove legacy URL handling
  get-resource.sh
Labels: approved, lgtm, size/S

#12 If RHCOS image is gzipped, decompress first before passing to qemu-img
  get-resource.sh
Labels: approved, lgtm, size/S

#13 Check file filename in cache instead of headers
  get-resource.sh
Labels: approved, lgtm, size/M

#14 Reinstate -L for curl to follow redirects
  get-resource.sh
Labels: approved, lgtm, size/XS

#15 Add xz support for FCOS
  Dockerfile
  Dockerfile.ocp
  get-resource.sh
Labels: approved, lgtm, size/S

#16 Turn off globbing on curl command
  get-resource.sh
Labels: approved, lgtm, size/XS
