Repository openshift/ironic-rhcos-downloader, pull requests merged in 2021-06, with the labels that each got.

#41 Bug 1969969: Use updated correct base image
  Dockerfile.ocp
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#42 Bug 1969969: Use base image from new registry
  Dockerfile.ocp
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#44 Bug 1968754: Unconditionally remove TMPDIR
  get-resource.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#40 Bug 1946079: Modify dhcp kernel args based on ipv4/ipv6
  Dockerfile.ocp
  get-resource.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#48 Bug 1972572: Fix image incompatibility between 4.7 and 4.8 while upgrade
  get-resource.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#52 Use 4.9 base image
  Dockerfile.ocp
Labels: approved, lgtm

#45 [release-4.7] Bug 1971549: Unconditionally remove TMPDIR
  get-resource.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
