Repository openshift/ironic-rhcos-downloader, pull requests merged in 2021-07, with the labels that each got.

#57 Do not succeed on HTTP failures
  get-resource.sh
Labels: approved, lgtm

#55 [release-4.7] Bug 1973367: Modify dhcp kernel args based on ipv4/ipv6
  Dockerfile.ocp
  get-resource.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#49 Add support to download and cache live iso images
  Dockerfile.ocp
  get-live-images.sh
Labels: approved, lgtm

#58 Remove unused env variable
  get-live-images.sh
Labels: approved, lgtm

#59 Add symlink to help second-level image cache to correctly download the images
  get-live-images.sh
Labels: approved, lgtm

#53 Bug 1963210: Add support for no_proxy
  get-resource.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
